---
version: '3.6'

services:
  jupyterlab:
    image: jupyter/datascience-notebook
    container_name: jupyterlab
    volumes:
      - ./src:/home/jovyan/work
    working_dir: /home/jovyan/work
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: start-notebook.sh --NotebookApp.token=''
